version: '3.6'
services:
  mysql:
    environment:
      - MYSQL_DATABASE=webapp
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=changeme
    command:
      - --table_definition_cache=100
      - --performance_schema=0
      - --default-authentication-plugin=mysql_native_password
      - --innodb_use_native_aio=0
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    container_name: mysqldb
    image: mysql

  backend:
    build:
      context: .
      dockerfile: ./backend/dev.Dockerfile
    volumes:
      - ./:/srv/app
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql      
      DB_PORT: 3306
      DB_USERNAME: dbuser
      DB_PASWORD: changeme
      DB: webapp
      PORTTOLISTENON: 3002
    ports:
      - "3002:3002"

  frontend:
    build:
      context: .
      dockerfile: ./frontend/dev.Dockerfile
    volumes:
      - ./:/srv/app
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://localhost:3002/
      PORT: 3001
    ports:
      - "3001:3001"
